server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

---

spring:
  jpa:
    generate-ddl: true
    show-sql: true

